name: GraalVM build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add Local PATH
        run: |
          echo "$PATH"
          echo "$GITHUB_WORKSPACE/" >> $GITHUB_PATH
          echo "$PATH"
      - name: Build # https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html
        run: gradlew :app:buildNativeLambda
      - name: Test
        run: gradlew test
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install CDK
        run: |
          npm install -g aws-cdk
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "us-east-1"
      - name: Deploy to AWS
        run: |
          cd infra
          cdk synth
          cdk deploy
          cd ..
          