name: GraalVM build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build # https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html
        run: gradlew :app:buildNativeLambda
      - name: Test
        run: gradlew test